# Generated by Django 5.2.4 on 2025-08-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="premium",
            field=models.CharField(default="no", max_length=2, verbose_name="Premium"),
        ),
    ]
