# Generated by Django 5.2.4 on 2025-08-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_producto_premium"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="premium",
            field=models.BooleanField(default=False, verbose_name="Premium"),
        ),
    ]
